export function generateShareLink(sopId, formData) {
  const payload = { sopId, formData };
  const encoded = btoa(unescape(encodeURIComponent(JSON.stringify(payload))));
  return `${window.location.href.split("#")[0]}#share=${encoded}`;
}

export function decodeShareLink() {
  const hash = window.location.hash;
  if (!hash.startsWith("#share=")) return null;
  try {
    const decoded = decodeURIComponent(escape(atob(hash.slice(7))));
    return JSON.parse(decoded);
  } catch { return null; }
}

export function downloadAsDocx(sop, formData, farmProfile) {
  const getVal = (id) => {
    const v = formData[id];
    if (Array.isArray(v)) return v.join(", ");
    return v || "";
  };
  let html = `<html><head><meta charset="utf-8"><style>
    body{font-family:Calibri,sans-serif;font-size:11pt;margin:1in;}
    h1{font-size:16pt;color:#14532d;border-bottom:2px solid #14532d;padding-bottom:6pt;}
    h2{font-size:13pt;color:#166534;margin-top:18pt;}
    h3{font-size:11pt;color:#374151;margin-top:12pt;}
    .field{margin-bottom:10pt;} .label{font-weight:bold;color:#374151;}
    .value{border-bottom:1px solid #ccc;min-width:200pt;display:inline-block;min-height:14pt;}
    table{width:100%;border-collapse:collapse;margin-top:10pt;font-size:9pt;}
    th{background:#14532d;color:white;padding:6pt;text-align:left;}
    td{border:1px solid #ccc;padding:5pt;}tr:nth-child(even){background:#f0fdf4;}
    .header-block{background:#f0fdf4;padding:12pt;border:1px solid #bbf7d0;margin-bottom:18pt;}
  </style></head><body>`;
  html += `<div class="header-block">`;
  if (farmProfile?.farm_name) html += `<h1>${farmProfile.farm_name}</h1>`;
  html += `<h1>${sop.title}</h1>`;
  html += `<p><strong>Reference:</strong> ${sop.ref}</p>`;
  if (farmProfile) {
    html += `<p><strong>Farm:</strong> ${farmProfile.farm_name || ""} | <strong>Address:</strong> ${farmProfile.address || ""}</p>`;
    html += `<p><strong>Operation Type:</strong> ${farmProfile.operation_type || ""} | <strong>Certifier:</strong> ${farmProfile.certifier || ""}</p>`;
  }
  html += `</div>`;
  for (const section of sop.sections) {
    html += `<h2>${section.title}</h2>`;
    for (const field of section.fields) {
      const val = getVal(field.id);
      html += `<div class="field"><span class="label">${field.label}: </span>`;
      html += val ? `<span>${val.replace(/\n/g, "<br/>")}</span>` : `<span class="value">&nbsp;</span>`;
      html += `</div>`;
    }
  }
  html += `<h2>${sop.log.title}</h2>`;
  html += `<table><tr>${sop.log.cols.map(c => `<th>${c}</th>`).join("")}</tr>`;
  for (let i = 0; i < 10; i++) html += `<tr>${sop.log.cols.map(() => `<td>&nbsp;</td>`).join("")}</tr>`;
  html += `</table>`;
  html += `<br/><p style="font-size:9pt;color:#9ca3af;">Generated by Farm Food Safety SOP System | ${new Date().toLocaleDateString()} | FSMA Produce Safety Rule compliant template</p>`;
  html += `</body></html>`;
  const blob = new Blob([html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a"); a.href = url;
  a.download = `${sop.title.replace(/[^a-z0-9]/gi, "_")}_SOP.doc`;
  a.click(); URL.revokeObjectURL(url);
}
